//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SquareApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int order_id { get; set; }
        public Nullable<int> user_id { get; set; }
        public Nullable<int> set_id { get; set; }
        public Nullable<System.DateTime> purchase_date { get; set; }
    
        public virtual Set Set { get; set; }
        public virtual User User { get; set; }
    }
}
