//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SquareApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tile
    {
        public int tile_id { get; set; }
        public Nullable<int> set_id { get; set; }
        public string url { get; set; }
    
        public virtual Set Set { get; set; }
    }
}
