//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SquareApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vSetWithTilesAndUser
    {
        public string name { get; set; }
        public Nullable<int> price { get; set; }
        public int set_id { get; set; }
        public Nullable<System.DateTime> upload_date { get; set; }
        public string userName { get; set; }
        public string email { get; set; }
        public Nullable<int> tile_id { get; set; }
        public string url { get; set; }
    }
}
